### ISSUE TITLE
Only download thumbnail

### ISSUE THREAD

**Issue by ItaloFan** [Anil-45/ImageCrawler#1]
As the title indicates, only thumbnails are downloaded. 
Is the program designed to download thumbnails? If so I'm sorry for disturbing. 
Besides it seems that it downloads only the first page as I set max_count to 100 I only get 27.

**Comment by Anil-45** [comment]
Hi @ItaloFan, I have tried running  `python main.py --object "cat, dog" --headless --out_dir "./images"  --max_count 125` and I see that 125 images are downloaded for each of the cat and dog. Can you tell me what you tried to download or did you change any configurations so that I can reproduce issue at my end?

**Comment by ItaloFan** [comment]
I just tried the example as you listed, without changing any configuration. 
I think it might be caused by my own network environment, as I'm in China and must use some additional technique (VPN for example) to visit specific websites.
Anyway I tried another tool and succeeded so it doesn't bother me anymore. Maybe it's meaningless to reproduce my case.
Thanks very much for your kind asking. 
Best wishes!
















At 2022-12-01 13:20:13, "Anil-45" ***@***.***> wrote:

Hi @ItaloFan, I have tried running python main.py --object "cat, dog" --headless --out_dir "./images" --max_count 125 and I see that 125 images are downloaded for each of the cat and dog. Can you tell me what you tried to download or did you change any configurations so that I can reproduce issue at my end?
